name: Tests backend

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_DB: MK_DB
          POSTGRES_USER: MK_User
          POSTGRES_PASSWORD: MK_Password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          sudo apt-get install gdal-bin
      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: MK_User
          POSTGRES_PASSWORD: MK_Password
          POSTGRES_DB: MK_DB
        run: |
          python manage.py collectstatic --noinput --settings=MK.settings.test
          coverage run --source='.' manage.py test --settings=MK.settings.test
          coverage report --fail-under=80
